version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=natalia
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
